theme: jekyll-theme-dinky
title: AskOmics
description: Integration and querying of heterogenous data with RDF/SPARQL
show_downloads: false

# Overriding these so it reads in a more sensible manner
github:
    is_project_page: true
    is_user_page: false
    repository_url: https://github.com/askomics/
